COUNTRY_ISO3_MAP: dict[str, str] = {
    # A
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Angola': 'AGO',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    # B
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Bolivia': 'BOL',
    'Bosnia And Herzegovina': 'BIH',
    'Brazil': 'BRA',
    'Bulgaria': 'BGR',
    # C
    'Cambodia': 'KHM',
    'Canada': 'CAN',
    'Chile': 'CHL',
    'China': 'CHN',
    'Colombia': 'COL',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Curacao': 'CUW',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Czechia': 'CZE',
    # D
    'Denmark': 'DNK',
    'Dominican Republic': 'DOM',
    # E
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Estonia': 'EST',
    'Ethiopia': 'ETH',
    # F
    'Finland': 'FIN',
    'France': 'FRA',
    # G
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Guatemala': 'GTM',
    # H
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    # I
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    # J
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    # K
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    # L
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    # M
    'Malaysia': 'MYS',
    'Malta': 'MLT',
    'Mauritius': 'MUS',
    'Mexico': 'MEX',
    'Moldova': 'MDA',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    # N
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Zealand': 'NZL',
    'Nigeria': 'NGA',
    'Norway': 'NOR',
    # O
    'Oman': 'OMN',
    # P
    'Pakistan': 'PAK',
    'Panama': 'PAN',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    # Q
    'Qatar': 'QAT',
    # R
    'Republic Of Korea': 'KOR',
    'Korea South': 'KOR',
    'South Korea': 'KOR',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Russian Federation': 'RUS',
    # S
    'Saudi Arabia': 'SAU',
    'Serbia': 'SRB',
    'Singapore': 'SGP',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'South Africa': 'ZAF',
    'South African Republic': 'ZAF',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    # T
    'Taiwan': 'TWN',
    'Taiwan Province Of China': 'TWN',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'Trinidad And Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkiye': 'TUR',
    'Turkey': 'TUR',
    # U
    'UAE': 'ARE',
    'United Arab Emirates': 'ARE',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    'United States Of America': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    # V
    'Venezuela': 'VEN',
    'Viet Nam': 'VNM',
    'Vietnam': 'VNM',
    # Z
    'Zimbabwe': 'ZWE',
    # Exporter countries (India-based primarily)
    'Bahamas': 'BHS',
    'Barbados': 'BRB',
    'Benin': 'BEN',
    'Cameroon': 'CMR',
    'Democratic Republic Of Congo': 'COD',
    'Ecuador': 'ECU',
    'Eritrea': 'ERI',
    'Ethiopia': 'ETH',
    'Gambia': 'GMB',
    'Honduras': 'HND',
    'Libya': 'LBY',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Mali': 'MLI',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Senegal': 'SEN',
    'Sudan': 'SDN',
    'Togo': 'TGO',
    'Zambia': 'ZMB',
}

PORT_LATLON_MAP: dict[str, tuple[float, float]] = {
    'New York':           (40.714,  -74.006),
    'London - Heathrow':  (51.477,   -0.461),
    'Los Angeles':        (33.929, -118.400),
    'Hamburg':            (53.550,    9.993),
    'Amsterdam/Schiphol': (52.308,    4.764),
    'Singapore':          ( 1.290,  103.850),
    'Sydney':             (-33.869, 151.209),
    'Melbourne':          (-37.814, 144.963),
    'Toronto':            (43.677,  -79.631),
    'Houston':            (29.760,  -95.370),
    'Frankfurt':          (50.033,    8.571),
    'Warsaw':             (52.166,   20.967),
    'Gdynia':             (54.520,   18.531),
    'Dubai':              (25.016,   55.137),
    'Almaty':             (43.222,   76.851),
    'Mukachevo/Ukraine':  (48.441,   22.720),
    'Delhi':              (28.644,   77.208),
    'Mumbai':             (18.955,   72.850),
    'Chennai':            (13.100,   80.183),
    'Bangalore':          (13.199,   77.706),
    'Hyderabad':          (17.453,   78.468),
    'Mundra':             (22.839,   69.724),
    'Cochin':             ( 9.966,   76.279),
    'Nhava Sheva':        (18.949,   72.951),
    'Bucharest':          (44.572,   26.102),
    'Dublin':             (53.426,   -6.244),
    'Auckland':           (-36.847, 174.763),
    'Oakland':            (37.804, -122.271),
    'Seoul':              (37.566,  126.978),
    'Cengkareng/Jakarta': (-6.125,  106.655),
}

POPULATION_M: dict[str, int] = {
    'India': 1428,
    'United States': 335,
    'Pakistan': 231,
    'Brazil': 215,
    'Bangladesh': 170,
    'Mexico': 130,
    'Philippines': 115,
    'Egypt': 104,
    'Viet Nam': 98,
    'Vietnam': 98,
    'Iran': 87,
    'Germany': 84,
    'France': 68,
    'United Kingdom': 67,
    'South Korea': 52,
    'Republic Of Korea': 52,
    'Colombia': 52,
    'Spain': 48,
    'Poland': 38,
    'Saudi Arabia': 36,
    'Malaysia': 33,
    'Australia': 26,
    'Romania': 19,
    'Kazakhstan': 19,
    'Chile': 19,
    'Netherlands': 17,
    'Belgium': 11,
    'Czech Republic': 11,
    'Hungary': 10,
    'Portugal': 10,
    'Sweden': 10,
    'Israel': 9,
    'UAE': 9,
    'United Arab Emirates': 9,
    'Singapore': 6,
    'New Zealand': 5,
    'Ireland': 5,
    'Norway': 5,
}

COLORS: dict[str, str] = {
    'dark_green':  '#1a6b3c',
    'mid_green':   '#2e9e5b',
    'light_green': '#b7f5d0',
    'gold':        '#f39c12',
    'blue':        '#2980b9',
    'red':         '#c0392b',
    'bg':          '#f8fffe',
}

SEQUENTIAL_GREEN: list[str] = [
    '#f0fff7', '#b7f5d0', '#82e0aa', '#4dc882',
    '#2e9e5b', '#1a6b3c', '#0f4025',
]

DIVERGING: list[str] = [
    '#c0392b', '#e74c3c', '#f39c12', '#f8fffe',
    '#82e0aa', '#2e9e5b', '#1a6b3c',
]
